### ISSUE TITLE
Publishing terminology

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#156]
In a few places the document talks about "publishing". What is meant by that?

     "If the client supports simulcast and wants to enable it for publishing" (Section 4.6)

     "the URL for connecting to the server-sent event resource for the published stream could" (Section 4.7)

     "It would be possible for an attacker in possession of authentication credentials valid
      to publish a WHIP stream" (Section 5)

If this is some terminology used in the broadcasting industry I think it would be good to introduce it in the Introduction. "Publish" is not used in other frameworks enabling SDP offer/answer.

**Comment by murillo128** [comment]
would just rename `publish` by `ingest`  be enough?

**Comment by cdh4u** [comment]
I think the suggested change would work.
