### ISSUE TITLE
Consistent usage of small and capital letters

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#157]
Please be consistent when using small and capital letters. For example, the text sometimes says "WHIP Client" and sometimes "WHIP client".

**Comment by murillo128** [comment]
changed, thank you!

**Comment by murillo128** [comment]
https://github.com/wish-wg/webrtc-http-ingest-protocol/commit/153ed0a9fd36cfb55ce2e5c924ae7fb540d63fb7
