### ISSUE TITLE
SDP renegotiations

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#158]
Section 1:

   "It is important to note that SDP renegotiations are not
   supported in WHIP, meaning that no modifications to the "m=" sections
   can be made after the initial SDP offer/answer exchange via HTTP POST
   is completed."

Q1: I think this text should e.g., be in a sub-section of Section 4.2, as a constraint.

Q2: As "m=" section sometimes also refers to the associated SDP attributes, Trickle ICE can be seen as a modification. I think it would be better to be more explicit and say that once the media has been negotiated, the WHIP client can only update the ICE candidates.

**Comment by murillo128** [comment]
as not only the ICE candidates, but the ice username/fragment can be updated when doing ice restarts, how about? 

```
"It is important to note that SDP renegotiations are not
supported in WHIP, meaning that no modifications to the "m=" sections
can be made after the initial SDP offer/answer exchange via HTTP POST
is completed and only ICE related information can be updated via HTTP PATCH requests as defined in Section 4.1."

**Comment by cdh4u** [comment]
It would probably need to be even more restrictive. For example, if you can't update the m= line, I assume it means that you cannot update the port of the local candidates when performing an ICE restart.

I also assume that WHIP does not allow update of the c= line, which means you cannot update the address of the local candidates either when performing an ICE restart.

(I will later post a separate Issue on ICE restart in general)

**Comment by murillo128** [comment]
wouldn't that be covered by
```
 only ICE related information can be updated via HTTP PATCH requests as defined in Section 4.1.
`` 
?

**Comment by cdh4u** [comment]
The port value in a candidate is ICE related information, and my understanding is that at least the host candidate port value cannot be updated.

**Comment by murillo128** [comment]
This is not normative text, just descriptive, so what actually can and can't be is defined in section 4.1 and RFC 8840.
