### ISSUE TITLE
SDP rtcp-rsize attribute

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#159]
The SDP example contains the SDP rtcp-rsize attribute. However, the usage is not defined, nor is RFC 5506 referenced.

My generic suggestion is to only use SDP information that is either mandatory, or is associated with a function that is described in the document, and remove the rest. That will avoid questions and misunderstandings ("it is used in the example, therefore it is mandatory") later.

**Comment by murillo128** [comment]
done
