### ISSUE TITLE
Trickle ICE support duplication

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#160]
Section 4.1.2:

   "In order to reduce the setup times, Trickle ICE support is RECOMMENDED for WHIP clients"

This has already been defined in Section 4.1. The advantages of Trickle ICE are also more or less duplicated. Perhaps remove it from Section 4.1?

**Comment by murillo128** [comment]
As ICE restart is not recommended in 4.1.3, would you be ok to remove it from section 4.1.2 instead?

```
In order to reduce the setup times, when using Trickle ICE the WHIP client SHOULD send the SDP offer as soon as possible containing either local gathered ICE candidates or an empty list of candidates.
```
