### ISSUE TITLE
Trickle ICE clarification

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#161]
Section 4.1.2:

   "In order to simplify the protocol, exchanging media server's gathered ICE candidates after sending the SDP answer is not supported."

Q1: I suggest to rewrite the sentence, to something like: "In order to simplify the protocol, the media server cannot send additional
ICE candidates to the WHIP client after it has sent the SDP answer".

Q2: This contradicts the earlier statement recommending the media server to support Trickle ICE. I guess it could be clarified that the support only applies to RECIVING trickled candidates from the client.

**Comment by murillo128** [comment]
Q1: the media server is not the entity that interacts in the signaling plane with the whip client, so it would have to be something like

```
In order to simplify the protocol, the WHIP session cannot signal additional ICE candidates to the WHIP client after the SDP answer has been sent.
```

does it look good to you?

Q2: In theory, the media server could do trickle ice even if it doesn't signal the gathered candidates to the whip client and just use the for sending STUN requests, right?
