### ISSUE TITLE
Full ICE/ICE lite use vs support clarification

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#162]
Section 4.1.2:

   "The media server MAY use ICE lite, while the WHIP client MUST implement full ICE."

Q1: This mixes procedures on what has to be implemented and what has to be used. Is a WHIP client allowed to use ICE lite?

Q2: I don't think this text belongs to the Trickle ICE section. I suggest moving it to Section 4.1.

**Comment by murillo128** [comment]
Fine with moving it to the 4.1 section.  Any sugestion on how to fix the sentence?
would :

```
The media server MAY implement ICE lite, while the WHIP client MUST implement full ICE."
````

be eough?

**Comment by cdh4u** [comment]
I prefer to use "support" instead of "implement". In addition to that I think it is important to specify what has to be USED, but I think it is clear that ICE is used for each session.

For the media server we could say "the media server SHOULD support full ICE, unless it is connected to the to the Internet with an IP address that is accessible by each WHIP client that is authorized to use it, in which case it MAY support only ICE lite".
