### ISSUE TITLE
WHIP specification version

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#166]
Section 4.2.2:

    "This version of the specification only supports..."

    ...and:

    "However, it would be possible for future revisions of this spec to allow.."

I don't think the text needs to talk about future versions etc, especially since there is no similar text for the other constraints in Section 4.2.

**Comment by murillo128** [comment]
This is one part of the specification that I would prefer to be future-proof, because I think that it will likely change in the near future if WHIP happens to gain traction. 

So if there is not a hard feeling against it, I would prefer to keep it as it is.

**Comment by murillo128** [comment]
I agree of removing the first `This version of the specification ` as we haven't specified any versioning in the spec. 

However, I feel that the second paragraph is valid, as we may update the rfc and allow more than a single stream/track and we specify the behaviour to be forward compatible if that happens.

We don't need to specify a different version number for this, as same that happens with other parameters, it is negotiated. I mean, we don't have a way of announcing if simulcast is supported by the media server, or a particular codec, we just specify how to fail if that happens.

**Comment by murillo128** [comment]
I agree, I have already removed the part that talked about potential future versions of this RFC.

**Comment by cdh4u** [comment]
Section 4 still talks about future versions in a couple of places:

   "The WHIP endpoints MUST return an "405 Method Not Allowed" response
   for any HTTP request method different than OPTIONS and POST on the
   endpoint URL in order to reserve their usage for future versions of
   this protocol specification."

...and:

   "The WHIP sessions MUST return an "405 Method Not Allowed" response
   for any HTTP request method different than PATCH and DELETE on the
   session URLs in order to reserve their usage for future versions of
   this protocol specification."

If you really want to talk about what may happen in the the future, my suggestion is to simply say "for future usage", or something like that.
