### ISSUE TITLE
WHIP session terminology overloading

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#168]
WHIP session seems to be used both to refer to "a session using WHIP", but also to some dynamically created function that performs actions, to which requests are sent etc. I think that is confusing, and suggest that we use different terminology when talking about a generic session and when talking about functions performing actions.

I realize there is a closed Issue (#145 ) related to this, but it is not related to "terminology overloading".

**Comment by murillo128** [comment]
The term "WHIP session" should only refer to the HTTP resource performing actions for an ongoing ingest session, do you have any example where it could be referring to a "a session using WHIP"?

**Comment by cdh4u** [comment]
In my opinion, e.g., the following text in Section 3 could be understood to refer to "a session using WHIP".

   "The following diagram illustrates the core operation of the WHIP protocol for initiating and terminating a WHIP session"

Section 4.2.3 talks about "partially successful WHIP sessions", which could also be understood to refer to "a session using WHIP".

**Comment by cdh4u** [comment]
Was there a resolution to this Issue?

**Comment by murillo128** [comment]
I think so, I removed the references when WHIP session could refer to an ingest session

**Comment by cdh4u** [comment]
I still think the Issue shall remain open during the WGLC, in case someone else has some input.
