### ISSUE TITLE
Response code when not supporting Trickle ICE or ICE restart

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#170]
Section 4.1.1.

"If the WHIP session supports either Trickle ICE or ICE restarts, but not both, it MUST return a "422 Unprocessable Content" response for the HTTP PATCH requests that are not supported as per [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110)] Section 15.5.21. If neither feature is supported, the WHIP session MUST return a "501 Not Implemented" response for such HTTP PATCH requests, as described in [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110)] Section 15.6.2."

Maybe I missunderstand the text, but why doesn't the WHIP session always send 501 if it receives a request for something it does not support? If a WHIP session e.g., receives a request for Trickle ICE, and it doesn't support it, the error code (422 vs 501) now depends on whether the WHIP session supports ICE Restart or not.

**Comment by murillo128** [comment]
This was recommended by the HTTP directorate. We can't return 501 because we implement the method. 

https://github.com/wish-wg/webrtc-http-ingest-protocol/issues/135

**Comment by cdh4u** [comment]
If so, I think it would be better to say "If the WHIP session does not support the HTTP PATCH request, it MUST send..."

**Comment by murillo128** [comment]
revisiting both HTTPDIR and genart feedback in https://github.com/wish-wg/webrtc-http-ingest-protocol/issues/135 i think that the following is wrong:

```
If neither feature is supported, the WHIP session MUST return a "501 Not Implemented" response for such HTTP PATCH requests, as described in [[RFC9110](https://www.rfc-editor.org/rfc/rfc9110)] Section 15.6.2."
```

The error code would depend of

- If the HTTP PATCH is implemented by the server (501 if not)
- If the HTTP PATCH is supported by the resource (405 if not)
- If the content type is supported for the PATCH request in the resource ( 415)

I think it is better to just remove the paragraph to not re-specify what is already defined in RFC 9910

wdyt?

**Comment by cdh4u** [comment]
In general, I don't need we need to repeat what is described elsewhere, so I have no problem removing the paragraph :)

Also, in general, if we DO refer to something that is specified elsewhere, I don't think we should use MUST/MAY/etc with capital letters, as we are referring to something that is specified elsewhere. Instead we should use small letters, and say something like "As specified in RFC XXXX, the client must do this and do that".

I know that people may have different opinions about this, and I am not religious about it, but it is feedback that I have received for my drafts :)

**Comment by murillo128** [comment]
me too, although the line is bit blurry sometimes so probably I might be using it wrongly sometimes.

**Comment by murillo128** [comment]
text removed, ok to close the issue?

**Comment by cdh4u** [comment]
It is fine for me. But, again, I don't think WGLC Issues shall be closed until the WGLC has finished, as others may have different opinions regarding the Issue solution.

**Comment by murillo128** [comment]
I prefer to close the issue so I can track what is pending or not. What I have done on other WG with had low  engagement is to create a new draft and issue another wglc to verify that everyone is ok with the changes.
