### ISSUE TITLE
SDP msid-semantic attribute

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#172]
I wrote an e-mail about this, but the issues has not bee fixed in -11, so I open an Issue for it.

The example in Section 4 contains the msid-semantic attribute in the offer and answer. However, the attribute was never standardized, so I assume it can be removed.

(This also applies to the whep draft)

**Comment by murillo128** [comment]
sorry, missed the email, they are removed now
