### ISSUE TITLE
SDP msid attribute

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#173]
In the SDP example in Section 4, the SDP msid attribute msid-id value is "-", indicating no MediaStream. What is the reason for that?

**Comment by murillo128** [comment]
Good catch! should not be like that, changed in https://github.com/wish-wg/webrtc-http-ingest-protocol/commit/bbbf7734ea53402fcab4203e5cae2825716f4b6d
