### ISSUE TITLE
PATCH instead of POST?

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#174]
Section 4.1.1. says:

   "If the HTTP POST to the WHIP session has a content type different
   than "application/trickle-ice-sdpfrag", the WHIP session MUST reject
   the HTTP POST request with a "415 Unsupported Media Type" error
   response.  If the SDP fragment is malformed, the WHIP session MUST
   reject the HTTP POST with a "400 Bad Request" error response."

I assume the text should be about FETCH instead of POST?

**Comment by murillo128** [comment]
Why FETCH? not following you on this

**Comment by murillo128** [comment]
you mean PATCH?

**Comment by cdh4u** [comment]
Yes, PATCH :)
