### ISSUE TITLE
BUNDLE example

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#177]
I think there are SDP BUNDLE-related errors in the POST SDP example in Section 4.

Q1: I don't think the ICE information shall be included in the bundle-only m- line

Q2: One of the m- lines shall NOT be bundle-only. 

I know that Section 4.2.1 says that each m- line shall contain bundle-only, but what is the reason for that? It is not aligned with JSEP, meaning that one has to modify the JSEP generated SDP before it is sent on the wire.

Q3: The port value of bundle-only m- lines shall be zero.

Q4: JSEP mandates the "ice2" ICE option to be included.

**Comment by murillo128** [comment]
Yes, I was thinking that we should revisit the `bundle-only` requirement, as the intention was to prevent having two different ice/dtls/srtp sessions which would be cumbersome to implement both on clients and servers.

Will have to check the specs, but seems we want to mandate bundle support on clients, and bundle-only usage on servers.

**Comment by cdh4u** [comment]
Just to clarify, I am not questioning the bundle-only requirement as such.

**Comment by murillo128** [comment]
I think that it would be better to refer to JSEP and state that `max-bundle` must be used

**Comment by murillo128** [comment]
bundle only on first m-section and 0 port on the rest have been fixed in the example.

**Comment by cdh4u** [comment]
In the example, the first m- line shall have a real port, and no bundle-only. The other m- lines shall have port 0 and bundle-only.

**Comment by murillo128** [comment]
sorry, bad recap of the commit, the example has the bundle-only and 0 port second m-line.

Regarding the port in the first m-line port, accorfing to JSEP for the initial offer:
```
If the "m=" section is marked as bundle-only, then the <port> value MUST be set to zero.
Otherwise, the <port> value is set to the port of the default ICE candidate for this "m=" section, 
but given that no candidates are available yet, the default port value of 9 (Discard) MUST be used,
as indicated in [[RFC8840](https://datatracker.ietf.org/doc/html/rfc8840)], [Section 4.1.1](https://www.rfc-editor.org/rfc/rfc8840#section-4.1.1).
```

**Comment by cdh4u** [comment]
Correct, if there is no candidate, the port value is set to 9.

However, I am not sure whether it is then correct to use port 9 in the PATCH request.

**Comment by murillo128** [comment]
I think it is correct given what is said in RFC8840:

```
the receiving agent MUST ignore any remaining content of the pseudo "m=" line, which is not defined in this document. This guarantees that the "application/trickle-ice-sdpfrag" bodies do not interfere with the Offer/Answer procedures as specified in [[RFC3264](https://www.rfc-editor.org/rfc/rfc8840.html#RFC3264)].

When sending the INFO request, the agent MAY, if already known to the agent, include the same content into the pseudo "m=" line as for the "m=" line in the corresponding Offer or Answer. However, since Trickle ICE might be decoupled from the Offer/Answer negotiation, the content might be unknown to the agent. In this case, the agent MUST include the following default values:

The media field is set to 'audio'.
The port value is set to '9'.
The proto value is set to 'RTP/AVP'.
The fmt field MUST appear only once and is set to '0'.
```
first, port is ignored anyway, second, the same content of m-line as in the offer must be sent, and if not know, 9.

**Comment by cdh4u** [comment]
Correct.
