### ISSUE TITLE
ice-option SDP attribute

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#178]
The SDP example in Section 4 shows ice-option as a media-level attribute. However, it is defined as a session-level attribute.

**Comment by murillo128** [comment]
I can change it, but this is comming directly from chrome though:
![image](https://github.com/wish-wg/webrtc-http-ingest-protocol/assets/1070835/e1da2098-8701-4758-9daa-2cfdfd7e11be)

**Comment by cdh4u** [comment]
That is interesting, and perhaps something that should be reported to the Chrome folks. However, I think our examples shall be aligned with the standard.

**Comment by murillo128** [comment]
agree, done
