### ISSUE TITLE
Provide support for consumers as well?

### ISSUE THREAD

**Issue by chriswiggins** [wish-wg/webrtc-http-ingest-protocol#18]
Reading through the draft spec, it appears apparent to me that this could also support **consumers** of WebRTC streams too.

In the case of an SFU, the process would be:

1. Request Offer (POST) -> Returns offer to client, with a header indicating a temporary Session ID
2. Send Answer (to Session ID Endpoint)-> Answer is then provided back to SFU

Would there be interest in a PR showing this flow? Or would this be best as a separate spec called webrtc-http-consumer-protocol?

**Comment by englishm** [comment]
Hi @chriswiggins!

Explicit support for egress of media to clients is expressly defined as out of scope for the WISH working group (and consequently, this document), as per the working group's [charter](https://datatracker.ietf.org/doc/charter-ietf-wish/):

> ...
> While there may be other problems that the proposed mechanism may solve or
nearly solve, such as video display clients connecting to the egress of a media
delivery network, adding explicit protocol support for those use cases is not
in scope for the WISH working group.

A document describing an egress flow using similar mechanisms could be drafted, but could not be adopted by the WISH working group under its current charter.

**Comment by chriswiggins** [comment]
Brilliant - thanks for that!
