### ISSUE TITLE
[WGLC -12] First m- line

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#183]
Section 4.1.2 says:

      "As per [RFC8829], only m-sections not marked as bundle-only can
      gather ICE candidates, so given that the "max-bundle" policy is
      being used, the SDP fragment will contain only the fist m-line of
      the bundle group."

It does not have to be the first m- line (assuming you are referring to the order of m- lines in the SDP)

**Comment by murillo128** [comment]
Would this be correct then?

```
 "As per [RFC8829], only m-sections not marked as bundle-only can
  gather ICE candidates, so given that the "max-bundle" policy is
  being used, the SDP fragment will contain only a single m-line of
  the bundle group."
```

**Comment by cdh4u** [comment]
BUNDLE refers the m- line as "offerer-tagged m- line". Maybe that could be used?

**Comment by murillo128** [comment]
perfect. will do the change later today

**Comment by murillo128** [comment]
done in https://github.com/wish-wg/webrtc-http-ingest-protocol/commit/2ecd6da74fb61d331bf5416881b163b6c3e30212

**Comment by cdh4u** [comment]
Looks ok.
