### ISSUE TITLE
[WGLC -12]: entity-tag

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#184]
Section 4.1.2 says:

   "Because the WHIP client needs to know the entity-tag associated with
   the ICE session in order to send a PATCH request containing new ICE
   candidates, it MUST wait and buffer any gathered candidates until it
   receives the HTTP response with the new entity-tag value to either
   the initial POST request or the last PATCH request performing an ICE
   restart."

Q1: The text is for trickle ICE, in which case it is optional for the WHIP session to support the entity-tag (per 4.1.1). 
So, if the WHIP session does not support ICE restart, the WHIP client may never receive an entity-tag.

**Comment by murillo128** [comment]
But the behavior of the client still applies, it has to wait for the HTTP POST response anyway

**Comment by cdh4u** [comment]
The client may not receive an entity-tag from the WHIP session, if the WHIP session does not support ICE restart. So, you can mandate that the client waits for the response to the initial POST request, but if the WHIP session does not support ICE restart you can not mandate the usage of the entity-tag.

**Comment by murillo128** [comment]
tentative change here https://github.com/wish-wg/webrtc-http-ingest-protocol/pull/187

**Comment by cdh4u** [comment]
The proposed change says that the client needs to wait for the entity-tag, and that the HTTP response may include the entity-tag. So, the problem still exists: if the client does not get the entity-tag, it cannot send a PATCH.

What about mandating the support of entity-tag also if the WHIP session supports trickle ICE?

**Comment by cdh4u** [comment]
> > What about mandating the support of entity-tag also if the WHIP session only supports trickle ICE (but does not support ICE restart)?
> 
> I think that many servers won't implement ice restarts and won't bother to add the etag, so better to put is as optional so the clients are able to cope with a missing one.

Ok, but then the text needs to be written in a way that does not mandate the client to wait/use the etag, if ICE restart is not supported.

> 
> > A question related to this: currently entity-tag support is required in the case of ICE restart. Do you really foresee ICE restart to happen so frequently that you would have overlapping HTTP requests?
> 
> I think it is an edge case of an edge case, but the concern was risen in the mailing list, and it is a valid one (I think)

Ok. Personally I think there is something wrong if an ICE client starts doing such frequent ICE restarts, but maybe someone is aware of valid scenarios.

**Comment by murillo128** [comment]
I think the text is a bit missleading, as the client needs to to wait for the initial response anyway in order to wait for the session resource url.  I will try to find a better text for explaining this

**Comment by murillo128** [comment]
changed to the following:

```
As the WHIP client needs to know the WHIP session URL associated with the ICE session in order to send a PATCH request containing new ICE candidates, it MUST wait and buffer any gathered candidates until the "201 Created" HTTP response to the initial POST request is received.
In order to lower the HTTP traffic and processing time required the WHIP client SHOULD send a single aggregated HTTP PATCH request with all the buffered ICE candidates once the response is received.
Additionaly, if ICE restarts are supported by the WHIP session, the WHIP client needs to know the entity-tag associated with the ICE session in order to send a PATCH request containing new ICE candidates, so it MUST also wait and buffer any gathered candidates until it receives the HTTP response with the new entity-tag value to the last PATCH request performing an ICE restart.
```

**Comment by cdh4u** [comment]
Looks ok.
