### ISSUE TITLE
Add more HTTP return code explanation？

### ISSUE THREAD

**Issue by notedit** [wish-wg/webrtc-http-ingest-protocol#20]
For example:

400 for  params error；
403 for Authentication fail；
And others.

**Comment by notedit** [comment]
Update:
409 for already  existed stream

**Comment by notedit** [comment]
@murillo128

**Comment by murillo128** [comment]
not sure if a mapping between the application errors and the http errors is really needed, as the semantics of each http error code is very well defined and the application error are very implementation specific.

For example, I would not return an error if there is already a published stream.

Anyway, i think it is an interesting topic, could you send an email to the whish-gw mailing list for discussion?

**Comment by notedit** [comment]
@murillo128  Where can i find the wish-wg mailing list?

**Comment by murillo128** [comment]
We had discussed this in the latest WISH meeting and the conclusion is that we should describe the server behaviour (and error code) when there is an error scenario in which the server could behave in different ways, but there is no need to define the error codes in case the behaviour of the server is clear and it is just a matter of mapping the error to the proper HTTP error code.

An example of the first case would be how to handle candidates with an unknown type address (for example ipv6) in which the server could behave in different ways: reject the complete patch request or just accept it and discard the candidate silently. This was addressed in the latest draft.

An example of the latest case would be about what error code to return in case the session is already terminated by the server and we receive a patch/delete request, in which case the behaviour of the server is clear (reject the request) and the developer should just check the proper http error response (404).

I will close this issue and let's as it is too broad and please open new ones for any case that should be handled in a case per case base.
