### ISSUE TITLE
Address remaining DISCUSS

### ISSUE THREAD

**Issue by seanturner** [wish-wg/webrtc-http-ingest-protocol#214]
Francesca revised here DISCUSS position; see [message](https://mailarchive.ietf.org/arch/msg/wish/TNWvi84aXj7Wulrk3GdyOLV8bAY/).

**Comment by nils-ohlmeier** [comment]
I believe with PR #215 closed we are good to go now.

**Comment by fpalombini** [comment]
we are! I'll remove my DISCUSS as soon as the update is posted to the datatracker :) thank you for the work!
