### ISSUE TITLE
Return code should indicate degree of offer acceptance

### ISSUE THREAD

**Issue by steely-glint** [wish-wg/webrtc-http-ingest-protocol#5]
It would ease client code/testing (especially on small devices) if the HTTP response indicated if the answer substantively changed the offer (eg disabled m-lines, deleted codecs, extensions removed etc).

200 would indicate that none of these had happened and the offer was OK
202 would indicate that the offer was accepted but the answer contains significant restrictions.

This would mean that a simple producer could be built that just used a template to generate the SDP offer and didn't need to parse or understand much of the SDP answer. (just fingerprint and ice candidate/ufrag/upass - although those could also be dispensed with).

**Comment by murillo128** [comment]
We would need to define what exactly do we consider "breaking changes" to the SDP. 

Breaking changes:
- disable m lines
- None of the codecs accepted for an m-line
Non-breaking changes:
- removed a codec from the offer (if the offerer sends several codecs it must be able to parse the response)
- removed an rtcp fb, in this case the sender can still send the rtcp packets and will be ignored by the receiver
- removed an header extension, same than in rtcp fb

Would it make more sense to mandate that in case that the any m-line is disabled or has no codec, the request must be rejected with a 400 not acceptable? If we accept it we would have an incomplete publication from the sender point of view

**Comment by steely-glint** [comment]
The problem with 400 is that it is strict NO - i.e. nothing can proceed. 

I can imagine a situation where it is ok to disable an m-line (secondary camera feed perhaps). 
Here a complex producer can decide what to do (it might depend on _which_ mline was disabled) and continue or DELETE
A simple producer could interpret 202 as a soft NO and issue an immediate DELETE.

**Comment by steely-glint** [comment]
My feeling is that any implied change in the answer should trigger a 202 - a simple offerer can then either give up,
 or a complex one should parse and interpret the SDP. 

The 200 means "All good, proceed as offered..."
The 202 means "you need an SDP parser to continue safely"

**Comment by murillo128** [comment]
I am fine with allowing partial publish (it may be even a policy of the ingestion server).

Regarding "changes that require parsing" we need to explicitly define what are those changes, or at the end all servers will choose to send  only one of the return codes that don't match your expectations anyway.

With respect to my list above, disabling an m-line or rejecting all codecs is something that can be trivially detected with a reg exp and don't require an sdp parsing.

Rejecting an rtp header extension or rtcp fb message can't be ignored on the sender.

What kind of changes in the sdp do you need to be aware off?

**Comment by steely-glint** [comment]
My goal here is to avoid parsing SDP on the producer end. 
I definitely want to avoid advising using a regexp to parse SDP.

I agree we need to define what constitutes a 'change', but we've made a decent start with your list above. I just don't think the breaking/non-breaking separation is the most useful one. The separation I'm interested in is 'Is this exactly what I asked for? Yes or No ' 
If Yes, I'll go ahead.
If No, I need to parse the SDP and evaluate if I want to proceed.

**Comment by murillo128** [comment]
if you dont do sdp parsing, you would need to do regexp for finding
ice/dtls info anyway.

**Comment by steely-glint** [comment]
(Ideally I'd like to make unnecessary to parse the answer at all. 
and I'm convinced it is perfectly possible).

But for the scope of this issue,
at minimum in the 200 case you can stop at the first m line.
There are a lot of small SDP parsers that can do this in VoIP phones RTSP clients etc. 

They are an order of magnitude simpler than the beast needed to cope with a full webRTC answer, that's even before you get to interpreting what all the different possible combinations of options in a full answer might actually _mean_.

If an implementer wants to use regexps that's up to them, but I don't think a standard should be reccomending it as best practice.

**Comment by murillo128** [comment]
I understand your religious resistance against SDP, but that's something I
can't change 🤣

The simple parsing should be prepared to extract the m-lines information
easily. The regexp was just a suggestion of implementation, not something I
would add to the spec.

Getting back to the list of changes, this is what we have so far:

- m lines disabled
- no codecs on m lines
- some codecs removed from m line
- some rtp header external removed
- some rtcp extensions removed

anything else missing?

**Comment by steely-glint** [comment]
For Video theo only one I can think of is the 
a=fmtp (packetization mode and level-id type settings)

There are a tonne of audio codec settings: 
a=ptime, 
a=maxptime, 
a=fmtp things like stereo, FEC, samplerate 

And of course :
a=sendrcv

**Comment by murillo128** [comment]
Re: opus, the only values that shall be enforced by the sender are:

- maxptime
- maxaveragebitrate

All the other parameters are "SHOULD".

**Comment by murillo128** [comment]
@steely-glint is this issue still relevant?

**Comment by steely-glint** [comment]
I do think so. Not having to parse the details of the SDP answer and compare it with a parsed offer is a significant code saving IMHO. 
If the reply status signals an negotiation happened (as opposed to acceptance of the offer), then simplistic clients can just treat it as a rejection (which is right because you aren't going to get the results you requested). 

Take a look at : https://github.com/pipe/whipi/blob/main/src/main/java/pe/pi/whipi/util/AnswerParser.java 
to see how _little_ code is actually needed if you can make this assumption.

**Comment by adamroach** [comment]
@steely-glint -- The issue is that I don't think what you're describing is ["the request has been accepted for processing, but the processing has not been completed"](https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.3), so we can't use 202 (as this would be "[using existing status codes even though the link between their semantics and the application's is tenuous at best](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-bcp56bis#section-4.6)". We could, in theory, "[document [a proposal for a new status code] as a separate HTTP extension, rather than as part of an application's specification](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-bcp56bis#section-4.6)", but that seems like an awful lot of work for this optimization (and I think it would be quite difficult to describe the semantics of "I accepted your request but I'm not happy about it" in an application-agnostic way.)

That's all about protocol mechanics, so let me address this from another angle as well: I don't think this kind of optimization is something we should be bothering with. Either your client can process SDP, and you can spend the various picoseconds and femtojoules to do so without anyone noticing or caring; or it can't, in which case a 202 is a catastrophic half-failure that we'll need to define baroque and complex procedures to unwind. I, for one, would definitely not like to have my network set up all the mechanics for a broadcast starting, and then need to reverse them all -- and their user-visible side effects! -- just because the broadcasting client can't deal with SDP.

**Comment by steely-glint** [comment]
I'd argue that 202 definition is accurate, but possibly not exactly what we want to convey here.

It isn't a matter of picoseconds or femto joules as much as person-years of dev time and testing I'm trying to save. 
The baroque and complex procedures are intrinsic to SDP. 

The selling point to WISH for me was that that it is simpler to implement in a hardware device than classic webRTC signalling. This isn't - it is just different. 

Requiring a full O/A SDP parser and the ability to do full blooded negotiation is adding needless complexity to the huge majority of simple cases for the sake of compatibility with an evolving and inscrutable standard - which is deeply undesirable in a hardware solution.

But as that's the route we are committed to I'll regretfully close this.
