### ISSUE TITLE
[CH] Section 4.4 (Technical)

### ISSUE THREAD

**Issue by murillo128** [wish-wg/webrtc-http-ingest-protocol#55]
he usability of the ICE server configuration seem to go far beyond WHIP. Also, in my opinion the way you configure your STUN/TURN servers is slightly outside the scope of core WHIP.

But, assuming you want to keep the text:

First, you should add references to where the STUN- and TURN server URIs are defined.

Second, I believe Link URIs have to be enclosed by < and >.

Third, I think the "ice-server" value is misleading. An ICE server is not the same thing as a STUN/TURN server. You don't even have to use ICE in order to support STUN/TURN.

Fourth, related to the third issue, perhaps you should use the "urn:ietf:params:whip:" appendix also for the STUN/TURN servers?

Fifth, you say that not all webrtc implementations may allow STUN/TURN server re-configuring after the offer has been created. But, does WebRTC even define a mechanism to programmatically configure the servers? If so, please add a reference. If not, please indicate that.

**Comment by murillo128** [comment]
Using WHIP without a valid TURN/STUN server configuration will fail in many cases, so In practice any WHIP service provider will also be providing STUN/TURN services to be used with.

WHIP allows sending the STUN/TURN server configuration in the HTTP request in order to not have to manualy configure the configuration manually o the client.

Moreover, some WHIP providers may want to restrict the usage of their TURN/STUN server and only provide short lived credentials that are only valid in the context of the WHIP session.

The term `ice-server` is taken from the W3C webrtc spec that uses the `iceServer` configuration property when creating the PC.

Regarding the `<` and `>`, yes, it is a typo and should be corrected.

Regarding the `urn:ietf:params:whip:` it was originally propossed like that but i was agreed that this could be used to configure other webrtc services and not only WHIP and it could be better to not have the urn be whip-specific

WebRTC w3c spec supports reconfiguration of the stun/turn server connection via 
https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-setconfiguration

**Comment by cdh4u** [comment]
> Using WHIP without a valid TURN/STUN server configuration will fail in many cases, so In practice any
> WHIP service provider will also be providing STUN/TURN services to be used with.

Won't the WHIP servers have a publicly available IP address in most cases? And, as the WHIP client is the one always establishing the media path, there should be no need for a STUN/TURN server in such cases. Or?
 
> The term `ice-server` is taken from the W3C webrtc spec that uses the `iceServer` configuration property
> when creating the PC.

Ok. I suggest adding a note to indicate that.

> Regarding the `urn:ietf:params:whip:` it was originally propossed like that but i was agreed that
> this could be used to configure other webrtc services and not only WHIP and it could be better
> to not have the urn be whip-specific

I suggest adding some text and point that out.

> WebRTC w3c spec supports reconfiguration of the stun/turn server connection via 
> https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-setconfiguration

Thanks! I suggest adding a reference,

**Comment by murillo128** [comment]
> Won't the WHIP servers have a publicly available IP address in most cases? And, as the WHIP client is the one always establishing the media path, there should be no need for a STUN/TURN server in such cases. Or?

Clients may be behind restricted firewalls which block UDP. It is easier to just deploy a TURN server to do TURN over TCP/TLS than implement ICE TCP on the media server (and ICE TLS is not standard anyway).

Also, you typically have less TURN servers than media servers, so it is easier to have them allowed by IP on the firewalls. In our case for example, our IPs of the media server pool are dinamic, so we must use TURN server IPs instead.

I will add notes for the other comments as suggested
