### ISSUE TITLE
Editorial: WHIP endpoint

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#62]
The draft talks about WHIP clients, WHIP endpoints and media servers.

Normally, an endpoint can be either a client or server. Could we say "WHIP server" instead?

**Comment by murillo128** [comment]
The nomenclature is reusing the "REST endpoints" term from HTTP REST APIs, so I think that WHIP endpoint is an appropriate term as it receives the POST request the same way as an REST enpoint would do.
