### ISSUE TITLE
Figure 4: Example ICE server configuration - Unwanted trailing semicolon

### ISSUE THREAD

**Issue by tkanakamalla** [wish-wg/webrtc-http-ingest-protocol#64]
In the example ICE server configuration of [4.4.  STUN/TURN server configuration](https://datatracker.ietf.org/doc/html/draft-ietf-wish-whip-02#section-4.4), every Link header is having a trailing semicolon `;`.
```
Link: stun:stun.example.net; rel="ice-server";
Link: turn:turn.example.net?transport=udp; rel="ice-server"; username="user"; credential: "myPassword"; credential-type: "password";
Link: turn:turn.example.net?transport=tcp; rel="ice-server"; username="user"; credential: "myPassword"; credential-type: "password";
Link: turns:turn.example.net?transport=tcp; rel="ice-server"; username="user"; credential: "myPassword"; credential-type: "password";
```

But as per [Link Serialisation in HTTP Headers](https://datatracker.ietf.org/doc/html/rfc8288#section-3) and [Link Header Field Examples](https://datatracker.ietf.org/doc/html/rfc8288#section-3.5) it seems there won't be any trailing semicolon in the Link header. This trailing semicolon could cause the parsing libraries (https://www.npmjs.com/package/parse-link-header) to create an extra param with empty string

**Comment by murillo128** [comment]
thank you @tkanakamalla ! @adamroach already fixed that in his editorial PR #65
