### ISSUE TITLE
ICE servers are known too late to be useful

### ISSUE THREAD

**Issue by jech** [wish-wg/webrtc-http-ingest-protocol#66]
Consider a client that does
```
offer = pc.createOffer();
pc.setLocalDescription(offer);
(answer, iceServers) = POST(pc.localDescription());
```
Since the ICE gathering process has started at the time of `setLocalDescription`, it is too late at this point to call `pc.setConfiguration`.  Thus, a way is needed to find the set of ICE servers before the offer is POSTed to the server.

In his mail of 12 July 2022, Sergio suggests a different procedure:
```
offer = pc.createOffer();
[answer,iceServers] = POST(offer)
pc.setConfigutation({iceServers});
pc.setLocalDescription(offer);
pc.setRemoteDescription(answer);
```
This alternate procedure should work, but it is somewhat unusual; thus, the spec should describe this procedure in detail, and indicate that this is the procedure that the WHIP client must use if it wishes to use the server-provided ICE servers.

What is more, with this procedure the posted offer does not contain any local candidates, which might imply that client-side Trickle ICE is a requirement, at least in some environments.  Again, this should be discussed in the draft.

**Comment by murillo128** [comment]
> What is more, with this procedure the posted offer does not contain any local candidates, which might imply that client-side Trickle ICE is a requirement, at least in some environments. Again, this should be discussed in the draft.

That is not true. If server is on a public IP address or behind a port forwarding NAT. The candidates sent by the server are enough to establish the ICE connection.

Gathering all the ICE candidates on the local offer are only required if the client does not support trickle and the server is behind of a NAT that requires hole punching.

I don't think we should explain how to use webrtc apis in the spec.

**Comment by jech** [comment]
> If server is on a public IP address or behind a port forwarding NAT. The candidates sent by the server are enough to establish the ICE connection.

So WHIP is restricted to the case where the server is on a public IP, with no firewall?  That would be fine with me, but if that's the case then IMHO it needs to be stated explicitly in the draft.

What happens if the client is on a restrictive network that only lets outgoing TCP through, which is unfortunately still the case in many university networks?  Are you assuming that the server supports passive TCP ICE?  If so, should that be mentioned in the draft somewhere?

**Comment by murillo128** [comment]
The turn server configuration via OPTIONS is not going to be removed.  

I can add a note like:

```
Note: Depending on the ICE Agent implementation, the WHIP client may need to wait for the setConfiguration to be set before calling the setLocalDespcription in order to avoid having to perform an ICE restart to apply the updated STUN/TURN server configuration on the next ICE gathering phase.
```
