### ISSUE TITLE
Please specify whether multiple streams are allowed

### ISSUE THREAD

**Issue by jech** [wish-wg/webrtc-http-ingest-protocol#68]
Until now, I've been working under the assumption that WHIP is limited to two tracks (audio+video) belonging to a single stream.  However, I'm now realising that there's nothing in the draft that says this is the case.

Please clarify which of the following is correct:

1. the client MUST offer at most one audio and one video track (possibly simulcast/SVC) belonging to a single stream; the server MUST return an error if there are more than two tracks;
2. the client MAY offer more than two tracks; how to handle this case is out of scope for WHIP, but the server MAY return an error if there are more than two tracks and the client MUST retry with just two tracks;
3. the client MAY offer multiple tracks in multiple streams, and the server MUST accept the multiple streams.

My preference is for (1) or (2), but I can live with (3).

**Comment by murillo128** [comment]
I had doubts regarding this, as I foresee that we will want to support multi tracks/streams in the near future (for multilanguage support for example)

I would propose something like.

```
While this version of the specification only supports a single audio and video track, in order to ensure forward compatibility, if the number of audio and or video tracks or number streams is not supported by the WHIP Endpoint, it MUST reject the HTTP POST request with a 406 Not Acceptable error code. 

Furthermore, the WHIP Endpoint SHOULD NOT reject individual "m=" sections as per {{!RFC8829}} section 5.3.1 in case there is any error processing the "m=" section, but reject the HTTP POST request with a 406 Not Acceptable error code to prevent having partially successful WHIP sessions.
`` 

I don't want to add the retry client logic to the client, as I think most of the times it would be better to inform the end user about the error and explicitly asking form confirmation before doing any change in the stream/track.

Note that this could happen today if the server supports audio only and the whip client is sending audio and video. I think that it is better to fail than just force retrying automatically with audio only.
