### ISSUE TITLE
Section 4. ICE consent freshness wording

### ISSUE THREAD

**Issue by nils-ohlmeier** [wish-wg/webrtc-http-ingest-protocol#75]
Section 4.
“Once a session is setup, ICE consent freshness [[RFC7675](https://www.ietf.org/archive/id/draft-ietf-wish-whip-04.html#RFC7675)] will be used to detect abrupt disconnection and DTLS teardown for session termination by either side.”

ICE consent freshness if implemented according to the default timing values from 7675 will report a disconnect only after 5 seconds and a failure only after 30 seconds. RFC7675 is only intended to prevent the whip client from sending for a long time without noticing that the media server for example crashed. 
Unfortunately Chrome has implemented 7675 with a lot more aggressive values, which makes people believe this allows for quick detection of connectivity issues.
I would suggest to replace “used to detect abrupt disconnection” with something like “used to detect disappearing client or endpoints”.

**Comment by murillo128** [comment]
Yes, that was the goal. I think that the confusion is about the usage of "abrupt", i was thinking more about "non-graceful disconnetions".
