### ISSUE TITLE
Section 4.1 move RFC8863 reference.

### ISSUE THREAD

**Issue by nils-ohlmeier** [wish-wg/webrtc-http-ingest-protocol#76]
Section 4.1
“The WHIP client MAY perform trickle ICE or ICE restarts [[RFC8863](https://www.ietf.org/archive/id/draft-ietf-wish-whip-04.html#RFC8863)] by sending an HTTP PATCH request…”

Why is there a reference to RFC8863, which specifies ICE PAC, here?
In general a reference to ICE PAC is useful, because this draft allows an offer without any candidates. So maybe that reference should go at the end of:
 “The initial offer by the WHIP client MAY be sent after the full ICE gathering is complete with the full list of ICE candidates, or it MAY only contain local candidates (or even an empty list of candidates).”

**Comment by murillo128** [comment]
I think it was a typo.

**Comment by murillo128** [comment]
I created a PR to fix the tricke ice reference and add the pac one as suggested.
