### ISSUE TITLE
Section 4.4 allow credentials for STUN servers

### ISSUE THREAD

**Issue by nils-ohlmeier** [wish-wg/webrtc-http-ingest-protocol#79]
Section 4.4
This section mentions “username” and “credential” if a TURN server is referenced. But technically even STUN servers can be operated with required authentication. So I think this should get changed to something more generic “if the referenced server requires authentication”.

**Comment by murillo128** [comment]
umm.. this text is taken from the w3c spec:

https://www.w3.org/TR/webrtc/#dom-rtciceserver-username

should we fix it in there too?
