### ISSUE TITLE
Is ETag really always required?

### ISSUE THREAD

**Issue by cameronelliott** [wish-wg/webrtc-http-ingest-protocol#85]
The draft says `Trickle ICE and ICE restart support is OPTIONAL for a WHIP resource.`

shortly after, the draft says: `The initial value of the entity-tag identifying the initial ICE session MUST be returned in an ETag header field in the 201 response to the initial POST request to the WHIP endpoint.`

Is the ETag header required on POST responses when neither trickle ice nor ice restart is supported by a WHIP resource?

ice-restart: yes & trickle-ice: yes.  -- ETag functionally required
ice-restart: no & trickle-ice: yes.  -- ETag functionally required
ice-restart: yes & trickle-ice: no.  -- ETag probably required
ice-restart: no & trickle-ice: no.  -- ETag not functionally required.

**So, if ETag is required in all four cases, can we consider making that explicit, even when it is not functionally required for WHIP resources not supporting trickle-ice or ice-restart?
If ETag is not required for the last case, or last two cases, can we make that explicit in the draft?**

I was tweaking `https://github.com/medooze/whip-js` to read the etag & generate if-match, as per the draft, but I started to scratch my head as to whether ETag output on the POST response is required from WHIP resources that don't support trickle-ice.

**Comment by murillo128** [comment]
being precise, the Etag would only be required if ICE restart is supported (not ICE tricke). I think we can make it explicit.

**Comment by cameronelliott** [comment]
Cool, I think it would be a small but helpful change for implementors.

**Comment by cameronelliott** [comment]
@murillo128 Thanks for closing/merging these issues & PRs. 
@murillo128 Also appreciate all you are creating with Wh*p

Oh, a small note, also there are three issues + two PRs in https://github.com/medooze/whip-js

Also, I wanted to get permission from you on this issue before submitting a PR: https://github.com/medooze/whip-js/issues/5 (implement if-match + etag)

**Comment by murillo128** [comment]
thank you @cameronelliott !

answered in whip-js repo
